services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile.nogpu
    ipc: host
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ../:/root/ros2_ws/src:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /usr/lib/wsl:/usr/lib/wsl
    devices:
      - /dev:/dev
    environment:
      - DISPLAY
      - "QT_X11_NO_MITSHM=1"
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - LIBGL_ALWAYS_SOFTWARE=true
      - ROS_LOG_DIR=/root/ros2_ws/src/logs
